version: "3"
services:
  app:
#    image: bitfinex-api
    container_name:  bitfinex-api
    build: .
    command: yarn server:dev
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    env_file:
      - .env
  fe:
#    image: bitfinex-fe
    container_name: bitfinex-fe
    build:
      dockerfile: fe.Dockerfile
    command: [nginx, '-g', 'daemon off;']
    ports:
      - "3002:80"