version: "3"
services:
  app:
    image: docker.io/itgovip/bitfinex-lending-api
    container_name:  bitfinex-lending-api
    platform: linux/amd64
    command: yarn server:dev
    ports:
      - "3001:3001"
    env_file:
      - .env
  fe:
    image: docker.io/itgovip/bitfinex-lending-fe
    container_name: bitfinex-lending-fe
    platform: linux/amd64
    command: [nginx, '-g', 'daemon off;']
    ports:
      - "3002:80"